/**
 * XmlException.java This file was generated by XMLSpy 2006sp2 Enterprise
 * Edition. YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE OVERWRITTEN WHEN
 * YOU RE-RUN CODE GENERATION. Refer to the XMLSpy Documentation for further
 * details. http://www.altova.com/xmlspy
 */

package com.jmex.model.collada.xml;

public class XmlException extends com.jmex.model.collada.AltovaException {

    private static final long serialVersionUID = 1L;
    public XmlException(String text) {
        super(text);
    }

    public XmlException(Exception other) {
        super(other);
    }
}
