/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class projectkyoto_jme3_mmd_nativelib_SkinUtil */

#ifndef _Included_projectkyoto_jme3_mmd_nativelib_SkinUtil
#define _Included_projectkyoto_jme3_mmd_nativelib_SkinUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     projectkyoto_jme3_mmd_nativelib_SkinUtil
 * Method:    copy
 * Signature: (Ljava/nio/Buffer;Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_projectkyoto_jme3_mmd_nativelib_SkinUtil_copy
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     projectkyoto_jme3_mmd_nativelib_SkinUtil
 * Method:    setSkin
 * Signature: (Ljava/nio/FloatBuffer;Ljava/nio/ShortBuffer;Ljava/nio/FloatBuffer;F)V
 */
JNIEXPORT void JNICALL Java_projectkyoto_jme3_mmd_nativelib_SkinUtil_setSkin
  (JNIEnv *, jclass, jobject, jobject, jobject, jfloat);

/*
 * Class:     projectkyoto_jme3_mmd_nativelib_SkinUtil
 * Method:    copyBoneMatrix
 * Signature: (Ljava/nio/FloatBuffer;Ljava/nio/FloatBuffer;Ljava/nio/ShortBuffer;)V
 */
JNIEXPORT void JNICALL Java_projectkyoto_jme3_mmd_nativelib_SkinUtil_copyBoneMatrix
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     projectkyoto_jme3_mmd_nativelib_SkinUtil
 * Method:    clear
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_projectkyoto_jme3_mmd_nativelib_SkinUtil_clear
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
