/**
 * bool4.java
 *
 * This file was generated by XMLSpy 2007sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.jmex.model.collada.schema;

import com.jmex.xml.types.SchemaString;

public class bool4 extends ListOfBools {

	public bool4() {
		super();
	}

	public bool4(String newValue) {
		super(newValue);
		validate();
	}

	public bool4(SchemaString newValue) {
		super(newValue);
		validate();
	}

	public void validate() {
	}
}
