/**
 * cg_float4.java
 *
 * This file was generated by XMLSpy 2007sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.jmex.model.collada.schema;

import com.jmex.xml.types.SchemaString;

public class cg_float4 extends cg_ListOfFloat {

	public cg_float4() {
		super();
	}

	public cg_float4(String newValue) {
		super(newValue);
		validate();
	}

	public cg_float4(SchemaString newValue) {
		super(newValue);
		validate();
	}

	public void validate() {
	}
}
