/**
 * cg_int.java
 *
 * This file was generated by XMLSpy 2007sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.jmex.model.collada.schema;

import com.jmex.xml.types.SchemaInt;

public class cg_int extends SchemaInt {

	public cg_int() {
		super();
	}

	public cg_int(String newValue) {
		super(newValue);
		validate();
	}

	public cg_int(SchemaInt newValue) {
		super(newValue);
		validate();
	}

	public void validate() {
	}
}
