/**
 * gl_func_type.java
 *
 * This file was generated by XMLSpy 2007sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.jmex.model.collada.schema;

import com.jmex.xml.types.SchemaString;

public class gl_func_type extends SchemaString {
	public static final int ENEVER = 0; /* NEVER */
	public static final int ELESS = 1; /* LESS */
	public static final int ELEQUAL = 2; /* LEQUAL */
	public static final int EEQUAL = 3; /* EQUAL */
	public static final int EGREATER = 4; /* GREATER */
	public static final int ENOTEQUAL = 5; /* NOTEQUAL */
	public static final int EGEQUAL = 6; /* GEQUAL */
	public static final int EALWAYS = 7; /* ALWAYS */

	public static String[] sEnumValues = {
		"NEVER",
		"LESS",
		"LEQUAL",
		"EQUAL",
		"GREATER",
		"NOTEQUAL",
		"GEQUAL",
		"ALWAYS",
	};

	public gl_func_type() {
		super();
	}

	public gl_func_type(String newValue) {
		super(newValue);
		validate();
	}

	public gl_func_type(SchemaString newValue) {
		super(newValue);
		validate();
	}

	public static int getEnumerationCount() {
		return sEnumValues.length;
	}

	public static String getEnumerationValue(int index) {
		return sEnumValues[index];
	}

	public static boolean isValidEnumerationValue(String val) {
		for (int i = 0; i < sEnumValues.length; i++) {
			if (val.equals(sEnumValues[i]))
				return true;
		}
		return false;
	}

	public void validate() {

		if (!isValidEnumerationValue(toString()))
			throw new com.jmex.xml.xml.XmlException("Value of gl_func_type is invalid.");
	}
}
