/**
 * gl_fog_coord_src_type.java
 *
 * This file was generated by XMLSpy 2007sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.jmex.model.collada.schema;

import com.jmex.xml.types.SchemaString;

public class gl_fog_coord_src_type extends SchemaString {
	public static final int EFOG_COORDINATE = 0; /* FOG_COORDINATE */
	public static final int EFRAGMENT_DEPTH = 1; /* FRAGMENT_DEPTH */

	public static String[] sEnumValues = {
		"FOG_COORDINATE",
		"FRAGMENT_DEPTH",
	};

	public gl_fog_coord_src_type() {
		super();
	}

	public gl_fog_coord_src_type(String newValue) {
		super(newValue);
		validate();
	}

	public gl_fog_coord_src_type(SchemaString newValue) {
		super(newValue);
		validate();
	}

	public static int getEnumerationCount() {
		return sEnumValues.length;
	}

	public static String getEnumerationValue(int index) {
		return sEnumValues[index];
	}

	public static boolean isValidEnumerationValue(String val) {
		for (int i = 0; i < sEnumValues.length; i++) {
			if (val.equals(sEnumValues[i]))
				return true;
		}
		return false;
	}

	public void validate() {

		if (!isValidEnumerationValue(toString()))
			throw new com.jmex.xml.xml.XmlException("Value of gl_fog_coord_src_type is invalid.");
	}
}
