/**
 * gles_rendertarget_common.java This file was generated by XMLSpy 2006sp2
 * Enterprise Edition. YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION. Refer to the XMLSpy
 * Documentation for further details. http://www.altova.com/xmlspy
 */

package com.jmex.model.collada.schema;

import com.jmex.model.collada.types.SchemaNCName;

public class gles_rendertarget_common extends SchemaNCName {

    private static final long serialVersionUID = 1L;

    public gles_rendertarget_common() {
        super();
    }

    public gles_rendertarget_common(String newValue) {
        super(newValue);
        validate();
    }

    public gles_rendertarget_common(SchemaNCName newValue) {
        super(newValue);
        validate();
    }

    public void validate() {
    }
}
