/**
 * gles_enumeration.java
 *
 * This file was generated by XMLSpy 2007sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.jmex.model.collada.schema;

import com.jmex.xml.types.SchemaString;

public class gles_enumeration extends SchemaString {

	public gles_enumeration() {
		super();
	}

	public gles_enumeration(String newValue) {
		super(newValue);
		validate();
	}

	public gles_enumeration(SchemaString newValue) {
		super(newValue);
		validate();
	}

	public void validate() {
	}
}
