/**
 * gles_rendertarget_common.java
 *
 * This file was generated by XMLSpy 2007sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.jmex.model.collada.schema;

import com.jmex.xml.types.SchemaNCName;

public class gles_rendertarget_common extends SchemaNCName {

	public gles_rendertarget_common() {
		super();
	}

	public gles_rendertarget_common(String newValue) {
		super(newValue);
		validate();
	}

	public gles_rendertarget_common(SchemaNCName newValue) {
		super(newValue);
		validate();
	}

	public void validate() {
	}
}
