/**
 * instance_rigid_constraintType.java This file was generated by XMLSpy 2006sp2
 * Enterprise Edition. YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION. Refer to the XMLSpy
 * Documentation for further details. http://www.altova.com/xmlspy
 */

package com.jmex.model.collada.schema;

import com.jmex.model.collada.types.SchemaNCName;

public class instance_rigid_constraintType extends
        com.jmex.model.collada.xml.Node {

    private static final long serialVersionUID = 1L;

    public instance_rigid_constraintType(instance_rigid_constraintType node) {
        super(node);
    }

    public instance_rigid_constraintType(org.w3c.dom.Node node) {
        super(node);
    }

    public instance_rigid_constraintType(org.w3c.dom.Document doc) {
        super(doc);
    }

    public instance_rigid_constraintType(
            com.jmex.model.collada.xml.Document doc, String namespaceURI,
            String prefix, String name) {
        super(doc, namespaceURI, prefix, name);
    }

    public void adjustPrefix() {
        for (org.w3c.dom.Node tmpNode = getDomFirstChild(Attribute, null,
                "constraint"); tmpNode != null; tmpNode = getDomNextChild(
                Attribute, null, "constraint", tmpNode)) {
            internalAdjustPrefix(tmpNode, false);
        }
        for (org.w3c.dom.Node tmpNode = getDomFirstChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema", "extra"); tmpNode != null; tmpNode = getDomNextChild(
                Element, "http://www.collada.org/2005/11/COLLADASchema",
                "extra", tmpNode)) {
            internalAdjustPrefix(tmpNode, true);
            new extraType(tmpNode).adjustPrefix();
        }
    }

    public static int getconstraintMinCount() {
        return 1;
    }

    public static int getconstraintMaxCount() {
        return 1;
    }

    public int getconstraintCount() {
        return getDomChildCount(Attribute, null, "constraint");
    }

    public boolean hasconstraint() {
        return hasDomChild(Attribute, null, "constraint");
    }

    public SchemaNCName newconstraint() {
        return new SchemaNCName();
    }

    public SchemaNCName getconstraintAt(int index) throws Exception {
        return new SchemaNCName(getDomNodeValue(dereference(getDomChildAt(
                Attribute, null, "constraint", index))));
    }

    public org.w3c.dom.Node getStartingconstraintCursor() throws Exception {
        return getDomFirstChild(Attribute, null, "constraint");
    }

    public org.w3c.dom.Node getAdvancedconstraintCursor(org.w3c.dom.Node curNode)
            throws Exception {
        return getDomNextChild(Attribute, null, "constraint", curNode);
    }

    public SchemaNCName getconstraintValueAtCursor(org.w3c.dom.Node curNode)
            throws Exception {
        if (curNode == null)
            throw new com.jmex.model.collada.xml.XmlException("Out of range");
        else
            return new SchemaNCName(getDomNodeValue(dereference(curNode)));
    }

    public SchemaNCName getconstraint() throws Exception {
        return getconstraintAt(0);
    }

    public void removeconstraintAt(int index) {
        removeDomChildAt(Attribute, null, "constraint", index);
    }

    public void removeconstraint() {
        while (hasconstraint())
            removeconstraintAt(0);
    }

    public void addconstraint(SchemaNCName value) {
        if (value.isNull() == false) {
            appendDomChild(Attribute, null, "constraint", value.toString());
        }
    }

    public void addconstraint(String value) throws Exception {
        addconstraint(new SchemaNCName(value));
    }

    public void insertconstraintAt(SchemaNCName value, int index) {
        insertDomChildAt(Attribute, null, "constraint", index, value.toString());
    }

    public void insertconstraintAt(String value, int index) throws Exception {
        insertconstraintAt(new SchemaNCName(value), index);
    }

    public void replaceconstraintAt(SchemaNCName value, int index) {
        replaceDomChildAt(Attribute, null, "constraint", index, value
                .toString());
    }

    public void replaceconstraintAt(String value, int index) throws Exception {
        replaceconstraintAt(new SchemaNCName(value), index);
    }

    public static int getextraMinCount() {
        return 0;
    }

    public static int getextraMaxCount() {
        return Integer.MAX_VALUE;
    }

    public int getextraCount() {
        return getDomChildCount(Element,
                "http://www.collada.org/2005/11/COLLADASchema", "extra");
    }

    public boolean hasextra() {
        return hasDomChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema", "extra");
    }

    public extraType newextra() {
        return new extraType(domNode.getOwnerDocument().createElementNS(
                "http://www.collada.org/2005/11/COLLADASchema", "extra"));
    }

    public extraType getextraAt(int index) throws Exception {
        return new extraType(
                dereference(getDomChildAt(Element,
                        "http://www.collada.org/2005/11/COLLADASchema",
                        "extra", index)));
    }

    public org.w3c.dom.Node getStartingextraCursor() throws Exception {
        return getDomFirstChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema", "extra");
    }

    public org.w3c.dom.Node getAdvancedextraCursor(org.w3c.dom.Node curNode)
            throws Exception {
        return getDomNextChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema", "extra",
                curNode);
    }

    public extraType getextraValueAtCursor(org.w3c.dom.Node curNode)
            throws Exception {
        if (curNode == null)
            throw new com.jmex.model.collada.xml.XmlException("Out of range");
        else
            return new extraType(dereference(curNode));
    }

    public extraType getextra() throws Exception {
        return getextraAt(0);
    }

    public void removeextraAt(int index) {
        removeDomChildAt(Element,
                "http://www.collada.org/2005/11/COLLADASchema", "extra", index);
    }

    public void removeextra() {
        while (hasextra())
            removeextraAt(0);
    }

    public void addextra(extraType value) {
        appendDomElement("http://www.collada.org/2005/11/COLLADASchema",
                "extra", value);
    }

    public void insertextraAt(extraType value, int index) {
        insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema",
                "extra", index, value);
    }

    public void replaceextraAt(extraType value, int index) {
        replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema",
                "extra", index, value);
    }

    private org.w3c.dom.Node dereference(org.w3c.dom.Node node) {
        return node;
    }
}
