/**
 * instance_materialType.java
 *
 * This file was generated by XMLSpy 2007sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.jmex.model.collada.schema;

import com.jmex.xml.types.SchemaNCName;
import com.jmex.xml.types.SchemaString;

public class instance_materialType extends com.jmex.xml.xml.Node {

	public instance_materialType(instance_materialType node) {
		super(node);
	}

	public instance_materialType(org.w3c.dom.Node node) {
		super(node);
	}

	public instance_materialType(org.w3c.dom.Document doc) {
		super(doc);
	}

	public instance_materialType(com.jmex.xml.xml.Document doc, String namespaceURI, String prefix, String name) {
		super(doc, namespaceURI, prefix, name);
	}
	
	public void adjustPrefix() {
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Attribute, null, "symbol" );
				tmpNode != null;
				tmpNode = getDomNextChild( Attribute, null, "symbol", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, false);
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Attribute, null, "target" );
				tmpNode != null;
				tmpNode = getDomNextChild( Attribute, null, "target", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, false);
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Attribute, null, "sid" );
				tmpNode != null;
				tmpNode = getDomNextChild( Attribute, null, "sid", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, false);
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Attribute, null, "name" );
				tmpNode != null;
				tmpNode = getDomNextChild( Attribute, null, "name", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, false);
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "bind" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "bind", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
			new bindType(tmpNode).adjustPrefix();
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "bind_vertex_input" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "bind_vertex_input", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
			new bind_vertex_inputType(tmpNode).adjustPrefix();
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "extra" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "extra", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
			new extraType(tmpNode).adjustPrefix();
		}
	}
	public void setXsiType() {
 		org.w3c.dom.Element el = (org.w3c.dom.Element) domNode;
		el.setAttributeNS("http://www.w3.org/2001/XMLSchema-instance", "xsi:type", "instance_material");
	}

	public static int getsymbolMinCount() {
		return 1;
	}

	public static int getsymbolMaxCount() {
		return 1;
	}

	public int getsymbolCount() {
		return getDomChildCount(Attribute, null, "symbol");
	}

	public boolean hassymbol() {
		return hasDomChild(Attribute, null, "symbol");
	}

	public SchemaNCName newsymbol() {
		return new SchemaNCName();
	}

	public SchemaNCName getsymbolAt(int index) throws Exception {
		return new SchemaNCName(getDomNodeValue(getDomChildAt(Attribute, null, "symbol", index)));
	}

	public org.w3c.dom.Node getStartingsymbolCursor() throws Exception {
		return getDomFirstChild(Attribute, null, "symbol" );
	}

	public org.w3c.dom.Node getAdvancedsymbolCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Attribute, null, "symbol", curNode );
	}

	public SchemaNCName getsymbolValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new SchemaNCName(getDomNodeValue(curNode));
	}

	public SchemaNCName getsymbol() throws Exception 
 {
		return getsymbolAt(0);
	}

	public void removesymbolAt(int index) {
		removeDomChildAt(Attribute, null, "symbol", index);
	}

	public void removesymbol() {
		removesymbolAt(0);
	}

	public org.w3c.dom.Node addsymbol(SchemaNCName value) {
		if( value.isNull() )
			return null;

		return  appendDomChild(Attribute, null, "symbol", value.toString());
	}

	public org.w3c.dom.Node addsymbol(String value) throws Exception {
		return addsymbol(new SchemaNCName(value));
	}

	public void insertsymbolAt(SchemaNCName value, int index) {
		insertDomChildAt(Attribute, null, "symbol", index, value.toString());
	}

	public void insertsymbolAt(String value, int index) throws Exception {
		insertsymbolAt(new SchemaNCName(value), index);
	}

	public void replacesymbolAt(SchemaNCName value, int index) {
		replaceDomChildAt(Attribute, null, "symbol", index, value.toString());
	}

	public void replacesymbolAt(String value, int index) throws Exception {
		replacesymbolAt(new SchemaNCName(value), index);
	}

	public static int gettargetMinCount() {
		return 1;
	}

	public static int gettargetMaxCount() {
		return 1;
	}

	public int gettargetCount() {
		return getDomChildCount(Attribute, null, "target");
	}

	public boolean hastarget() {
		return hasDomChild(Attribute, null, "target");
	}

	public SchemaString newtarget() {
		return new SchemaString();
	}

	public SchemaString gettargetAt(int index) throws Exception {
		return new SchemaString(getDomNodeValue(getDomChildAt(Attribute, null, "target", index)));
	}

	public org.w3c.dom.Node getStartingtargetCursor() throws Exception {
		return getDomFirstChild(Attribute, null, "target" );
	}

	public org.w3c.dom.Node getAdvancedtargetCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Attribute, null, "target", curNode );
	}

	public SchemaString gettargetValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new SchemaString(getDomNodeValue(curNode));
	}

	public SchemaString gettarget() throws Exception 
 {
		return gettargetAt(0);
	}

	public void removetargetAt(int index) {
		removeDomChildAt(Attribute, null, "target", index);
	}

	public void removetarget() {
		removetargetAt(0);
	}

	public org.w3c.dom.Node addtarget(SchemaString value) {
		if( value.isNull() )
			return null;

		return  appendDomChild(Attribute, null, "target", value.toString());
	}

	public org.w3c.dom.Node addtarget(String value) throws Exception {
		return addtarget(new SchemaString(value));
	}

	public void inserttargetAt(SchemaString value, int index) {
		insertDomChildAt(Attribute, null, "target", index, value.toString());
	}

	public void inserttargetAt(String value, int index) throws Exception {
		inserttargetAt(new SchemaString(value), index);
	}

	public void replacetargetAt(SchemaString value, int index) {
		replaceDomChildAt(Attribute, null, "target", index, value.toString());
	}

	public void replacetargetAt(String value, int index) throws Exception {
		replacetargetAt(new SchemaString(value), index);
	}

	public static int getsidMinCount() {
		return 0;
	}

	public static int getsidMaxCount() {
		return 1;
	}

	public int getsidCount() {
		return getDomChildCount(Attribute, null, "sid");
	}

	public boolean hassid() {
		return hasDomChild(Attribute, null, "sid");
	}

	public SchemaNCName newsid() {
		return new SchemaNCName();
	}

	public SchemaNCName getsidAt(int index) throws Exception {
		return new SchemaNCName(getDomNodeValue(getDomChildAt(Attribute, null, "sid", index)));
	}

	public org.w3c.dom.Node getStartingsidCursor() throws Exception {
		return getDomFirstChild(Attribute, null, "sid" );
	}

	public org.w3c.dom.Node getAdvancedsidCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Attribute, null, "sid", curNode );
	}

	public SchemaNCName getsidValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new SchemaNCName(getDomNodeValue(curNode));
	}

	public SchemaNCName getsid() throws Exception 
 {
		return getsidAt(0);
	}

	public void removesidAt(int index) {
		removeDomChildAt(Attribute, null, "sid", index);
	}

	public void removesid() {
		removesidAt(0);
	}

	public org.w3c.dom.Node addsid(SchemaNCName value) {
		if( value.isNull() )
			return null;

		return  appendDomChild(Attribute, null, "sid", value.toString());
	}

	public org.w3c.dom.Node addsid(String value) throws Exception {
		return addsid(new SchemaNCName(value));
	}

	public void insertsidAt(SchemaNCName value, int index) {
		insertDomChildAt(Attribute, null, "sid", index, value.toString());
	}

	public void insertsidAt(String value, int index) throws Exception {
		insertsidAt(new SchemaNCName(value), index);
	}

	public void replacesidAt(SchemaNCName value, int index) {
		replaceDomChildAt(Attribute, null, "sid", index, value.toString());
	}

	public void replacesidAt(String value, int index) throws Exception {
		replacesidAt(new SchemaNCName(value), index);
	}

	public static int getnameMinCount() {
		return 0;
	}

	public static int getnameMaxCount() {
		return 1;
	}

	public int getnameCount() {
		return getDomChildCount(Attribute, null, "name");
	}

	public boolean hasname() {
		return hasDomChild(Attribute, null, "name");
	}

	public SchemaNCName newname() {
		return new SchemaNCName();
	}

	public SchemaNCName getnameAt(int index) throws Exception {
		return new SchemaNCName(getDomNodeValue(getDomChildAt(Attribute, null, "name", index)));
	}

	public org.w3c.dom.Node getStartingnameCursor() throws Exception {
		return getDomFirstChild(Attribute, null, "name" );
	}

	public org.w3c.dom.Node getAdvancednameCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Attribute, null, "name", curNode );
	}

	public SchemaNCName getnameValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new SchemaNCName(getDomNodeValue(curNode));
	}

	public SchemaNCName getname() throws Exception 
 {
		return getnameAt(0);
	}

	public void removenameAt(int index) {
		removeDomChildAt(Attribute, null, "name", index);
	}

	public void removename() {
		removenameAt(0);
	}

	public org.w3c.dom.Node addname(SchemaNCName value) {
		if( value.isNull() )
			return null;

		return  appendDomChild(Attribute, null, "name", value.toString());
	}

	public org.w3c.dom.Node addname(String value) throws Exception {
		return addname(new SchemaNCName(value));
	}

	public void insertnameAt(SchemaNCName value, int index) {
		insertDomChildAt(Attribute, null, "name", index, value.toString());
	}

	public void insertnameAt(String value, int index) throws Exception {
		insertnameAt(new SchemaNCName(value), index);
	}

	public void replacenameAt(SchemaNCName value, int index) {
		replaceDomChildAt(Attribute, null, "name", index, value.toString());
	}

	public void replacenameAt(String value, int index) throws Exception {
		replacenameAt(new SchemaNCName(value), index);
	}

	public static int getbindMinCount() {
		return 0;
	}

	public static int getbindMaxCount() {
		return Integer.MAX_VALUE;
	}

	public int getbindCount() {
		return getDomChildCount(Element, "http://www.collada.org/2005/11/COLLADASchema", "bind");
	}

	public boolean hasbind() {
		return hasDomChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "bind");
	}

	public bindType newbind() {
		return new bindType(domNode.getOwnerDocument().createElementNS("http://www.collada.org/2005/11/COLLADASchema", "bind"));
	}

	public bindType getbindAt(int index) throws Exception {
		return new bindType(getDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "bind", index));
	}

	public org.w3c.dom.Node getStartingbindCursor() throws Exception {
		return getDomFirstChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "bind" );
	}

	public org.w3c.dom.Node getAdvancedbindCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "bind", curNode );
	}

	public bindType getbindValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new bindType(curNode);
	}

	public bindType getbind() throws Exception 
 {
		return getbindAt(0);
	}

	public void removebindAt(int index) {
		removeDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "bind", index);
	}

	public void removebind() {
		while (hasbind())
			removebindAt(0);
	}

	public org.w3c.dom.Node addbind(bindType value) {
		return appendDomElement("http://www.collada.org/2005/11/COLLADASchema", "bind", value);
	}

	public void insertbindAt(bindType value, int index) {
		insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "bind", index, value);
	}

	public void replacebindAt(bindType value, int index) {
		replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "bind", index, value);
	}

	public static int getbind_vertex_inputMinCount() {
		return 0;
	}

	public static int getbind_vertex_inputMaxCount() {
		return Integer.MAX_VALUE;
	}

	public int getbind_vertex_inputCount() {
		return getDomChildCount(Element, "http://www.collada.org/2005/11/COLLADASchema", "bind_vertex_input");
	}

	public boolean hasbind_vertex_input() {
		return hasDomChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "bind_vertex_input");
	}

	public bind_vertex_inputType newbind_vertex_input() {
		return new bind_vertex_inputType(domNode.getOwnerDocument().createElementNS("http://www.collada.org/2005/11/COLLADASchema", "bind_vertex_input"));
	}

	public bind_vertex_inputType getbind_vertex_inputAt(int index) throws Exception {
		return new bind_vertex_inputType(getDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "bind_vertex_input", index));
	}

	public org.w3c.dom.Node getStartingbind_vertex_inputCursor() throws Exception {
		return getDomFirstChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "bind_vertex_input" );
	}

	public org.w3c.dom.Node getAdvancedbind_vertex_inputCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "bind_vertex_input", curNode );
	}

	public bind_vertex_inputType getbind_vertex_inputValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new bind_vertex_inputType(curNode);
	}

	public bind_vertex_inputType getbind_vertex_input() throws Exception 
 {
		return getbind_vertex_inputAt(0);
	}

	public void removebind_vertex_inputAt(int index) {
		removeDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "bind_vertex_input", index);
	}

	public void removebind_vertex_input() {
		while (hasbind_vertex_input())
			removebind_vertex_inputAt(0);
	}

	public org.w3c.dom.Node addbind_vertex_input(bind_vertex_inputType value) {
		return appendDomElement("http://www.collada.org/2005/11/COLLADASchema", "bind_vertex_input", value);
	}

	public void insertbind_vertex_inputAt(bind_vertex_inputType value, int index) {
		insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "bind_vertex_input", index, value);
	}

	public void replacebind_vertex_inputAt(bind_vertex_inputType value, int index) {
		replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "bind_vertex_input", index, value);
	}

	public static int getextraMinCount() {
		return 0;
	}

	public static int getextraMaxCount() {
		return Integer.MAX_VALUE;
	}

	public int getextraCount() {
		return getDomChildCount(Element, "http://www.collada.org/2005/11/COLLADASchema", "extra");
	}

	public boolean hasextra() {
		return hasDomChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "extra");
	}

	public extraType newextra() {
		return new extraType(domNode.getOwnerDocument().createElementNS("http://www.collada.org/2005/11/COLLADASchema", "extra"));
	}

	public extraType getextraAt(int index) throws Exception {
		return new extraType(getDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "extra", index));
	}

	public org.w3c.dom.Node getStartingextraCursor() throws Exception {
		return getDomFirstChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "extra" );
	}

	public org.w3c.dom.Node getAdvancedextraCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "extra", curNode );
	}

	public extraType getextraValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new extraType(curNode);
	}

	public extraType getextra() throws Exception 
 {
		return getextraAt(0);
	}

	public void removeextraAt(int index) {
		removeDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "extra", index);
	}

	public void removeextra() {
		while (hasextra())
			removeextraAt(0);
	}

	public org.w3c.dom.Node addextra(extraType value) {
		return appendDomElement("http://www.collada.org/2005/11/COLLADASchema", "extra", value);
	}

	public void insertextraAt(extraType value, int index) {
		insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "extra", index, value);
	}

	public void replaceextraAt(extraType value, int index) {
		replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "extra", index, value);
	}

}
