/**
 * orthographicType.java
 *
 * This file was generated by XMLSpy 2007sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.jmex.model.collada.schema;


public class orthographicType extends com.jmex.xml.xml.Node {

	public orthographicType(orthographicType node) {
		super(node);
	}

	public orthographicType(org.w3c.dom.Node node) {
		super(node);
	}

	public orthographicType(org.w3c.dom.Document doc) {
		super(doc);
	}

	public orthographicType(com.jmex.xml.xml.Document doc, String namespaceURI, String prefix, String name) {
		super(doc, namespaceURI, prefix, name);
	}
	
	public void adjustPrefix() {
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "xmag" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "xmag", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
			new TargetableFloat(tmpNode).adjustPrefix();
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "ymag" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "ymag", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
			new TargetableFloat(tmpNode).adjustPrefix();
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "aspect_ratio" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "aspect_ratio", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
			new TargetableFloat(tmpNode).adjustPrefix();
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "znear" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "znear", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
			new TargetableFloat(tmpNode).adjustPrefix();
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "zfar" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "zfar", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
			new TargetableFloat(tmpNode).adjustPrefix();
		}
	}
	public void setXsiType() {
 		org.w3c.dom.Element el = (org.w3c.dom.Element) domNode;
		el.setAttributeNS("http://www.w3.org/2001/XMLSchema-instance", "xsi:type", "orthographic");
	}

	public static int getxmagMinCount() {
		return 1;
	}

	public static int getxmagMaxCount() {
		return 1;
	}

	public int getxmagCount() {
		return getDomChildCount(Element, "http://www.collada.org/2005/11/COLLADASchema", "xmag");
	}

	public boolean hasxmag() {
		return hasDomChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "xmag");
	}

	public TargetableFloat newxmag() {
		return new TargetableFloat(domNode.getOwnerDocument().createElementNS("http://www.collada.org/2005/11/COLLADASchema", "xmag"));
	}

	public TargetableFloat getxmagAt(int index) throws Exception {
		return new TargetableFloat(getDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "xmag", index));
	}

	public org.w3c.dom.Node getStartingxmagCursor() throws Exception {
		return getDomFirstChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "xmag" );
	}

	public org.w3c.dom.Node getAdvancedxmagCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "xmag", curNode );
	}

	public TargetableFloat getxmagValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new TargetableFloat(curNode);
	}

	public TargetableFloat getxmag() throws Exception 
 {
		return getxmagAt(0);
	}

	public void removexmagAt(int index) {
		removeDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "xmag", index);
	}

	public void removexmag() {
		removexmagAt(0);
	}

	public org.w3c.dom.Node addxmag(TargetableFloat value) {
		return appendDomElement("http://www.collada.org/2005/11/COLLADASchema", "xmag", value);
	}

	public void insertxmagAt(TargetableFloat value, int index) {
		insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "xmag", index, value);
	}

	public void replacexmagAt(TargetableFloat value, int index) {
		replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "xmag", index, value);
	}

	public static int getymagMinCount() {
		return 1;
	}

	public static int getymagMaxCount() {
		return 1;
	}

	public int getymagCount() {
		return getDomChildCount(Element, "http://www.collada.org/2005/11/COLLADASchema", "ymag");
	}

	public boolean hasymag() {
		return hasDomChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "ymag");
	}

	public TargetableFloat newymag() {
		return new TargetableFloat(domNode.getOwnerDocument().createElementNS("http://www.collada.org/2005/11/COLLADASchema", "ymag"));
	}

	public TargetableFloat getymagAt(int index) throws Exception {
		return new TargetableFloat(getDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "ymag", index));
	}

	public org.w3c.dom.Node getStartingymagCursor() throws Exception {
		return getDomFirstChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "ymag" );
	}

	public org.w3c.dom.Node getAdvancedymagCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "ymag", curNode );
	}

	public TargetableFloat getymagValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new TargetableFloat(curNode);
	}

	public TargetableFloat getymag() throws Exception 
 {
		return getymagAt(0);
	}

	public void removeymagAt(int index) {
		removeDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "ymag", index);
	}

	public void removeymag() {
		removeymagAt(0);
	}

	public org.w3c.dom.Node addymag(TargetableFloat value) {
		return appendDomElement("http://www.collada.org/2005/11/COLLADASchema", "ymag", value);
	}

	public void insertymagAt(TargetableFloat value, int index) {
		insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "ymag", index, value);
	}

	public void replaceymagAt(TargetableFloat value, int index) {
		replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "ymag", index, value);
	}

	public static int getaspect_ratioMinCount() {
		return 1;
	}

	public static int getaspect_ratioMaxCount() {
		return 1;
	}

	public int getaspect_ratioCount() {
		return getDomChildCount(Element, "http://www.collada.org/2005/11/COLLADASchema", "aspect_ratio");
	}

	public boolean hasaspect_ratio() {
		return hasDomChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "aspect_ratio");
	}

	public TargetableFloat newaspect_ratio() {
		return new TargetableFloat(domNode.getOwnerDocument().createElementNS("http://www.collada.org/2005/11/COLLADASchema", "aspect_ratio"));
	}

	public TargetableFloat getaspect_ratioAt(int index) throws Exception {
		return new TargetableFloat(getDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "aspect_ratio", index));
	}

	public org.w3c.dom.Node getStartingaspect_ratioCursor() throws Exception {
		return getDomFirstChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "aspect_ratio" );
	}

	public org.w3c.dom.Node getAdvancedaspect_ratioCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "aspect_ratio", curNode );
	}

	public TargetableFloat getaspect_ratioValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new TargetableFloat(curNode);
	}

	public TargetableFloat getaspect_ratio() throws Exception 
 {
		return getaspect_ratioAt(0);
	}

	public void removeaspect_ratioAt(int index) {
		removeDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "aspect_ratio", index);
	}

	public void removeaspect_ratio() {
		removeaspect_ratioAt(0);
	}

	public org.w3c.dom.Node addaspect_ratio(TargetableFloat value) {
		return appendDomElement("http://www.collada.org/2005/11/COLLADASchema", "aspect_ratio", value);
	}

	public void insertaspect_ratioAt(TargetableFloat value, int index) {
		insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "aspect_ratio", index, value);
	}

	public void replaceaspect_ratioAt(TargetableFloat value, int index) {
		replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "aspect_ratio", index, value);
	}

	public static int getznearMinCount() {
		return 1;
	}

	public static int getznearMaxCount() {
		return 1;
	}

	public int getznearCount() {
		return getDomChildCount(Element, "http://www.collada.org/2005/11/COLLADASchema", "znear");
	}

	public boolean hasznear() {
		return hasDomChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "znear");
	}

	public TargetableFloat newznear() {
		return new TargetableFloat(domNode.getOwnerDocument().createElementNS("http://www.collada.org/2005/11/COLLADASchema", "znear"));
	}

	public TargetableFloat getznearAt(int index) throws Exception {
		return new TargetableFloat(getDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "znear", index));
	}

	public org.w3c.dom.Node getStartingznearCursor() throws Exception {
		return getDomFirstChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "znear" );
	}

	public org.w3c.dom.Node getAdvancedznearCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "znear", curNode );
	}

	public TargetableFloat getznearValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new TargetableFloat(curNode);
	}

	public TargetableFloat getznear() throws Exception 
 {
		return getznearAt(0);
	}

	public void removeznearAt(int index) {
		removeDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "znear", index);
	}

	public void removeznear() {
		removeznearAt(0);
	}

	public org.w3c.dom.Node addznear(TargetableFloat value) {
		return appendDomElement("http://www.collada.org/2005/11/COLLADASchema", "znear", value);
	}

	public void insertznearAt(TargetableFloat value, int index) {
		insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "znear", index, value);
	}

	public void replaceznearAt(TargetableFloat value, int index) {
		replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "znear", index, value);
	}

	public static int getzfarMinCount() {
		return 1;
	}

	public static int getzfarMaxCount() {
		return 1;
	}

	public int getzfarCount() {
		return getDomChildCount(Element, "http://www.collada.org/2005/11/COLLADASchema", "zfar");
	}

	public boolean haszfar() {
		return hasDomChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "zfar");
	}

	public TargetableFloat newzfar() {
		return new TargetableFloat(domNode.getOwnerDocument().createElementNS("http://www.collada.org/2005/11/COLLADASchema", "zfar"));
	}

	public TargetableFloat getzfarAt(int index) throws Exception {
		return new TargetableFloat(getDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "zfar", index));
	}

	public org.w3c.dom.Node getStartingzfarCursor() throws Exception {
		return getDomFirstChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "zfar" );
	}

	public org.w3c.dom.Node getAdvancedzfarCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "zfar", curNode );
	}

	public TargetableFloat getzfarValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new TargetableFloat(curNode);
	}

	public TargetableFloat getzfar() throws Exception 
 {
		return getzfarAt(0);
	}

	public void removezfarAt(int index) {
		removeDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "zfar", index);
	}

	public void removezfar() {
		removezfarAt(0);
	}

	public org.w3c.dom.Node addzfar(TargetableFloat value) {
		return appendDomElement("http://www.collada.org/2005/11/COLLADASchema", "zfar", value);
	}

	public void insertzfarAt(TargetableFloat value, int index) {
		insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "zfar", index, value);
	}

	public void replacezfarAt(TargetableFloat value, int index) {
		replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "zfar", index, value);
	}

}
