/**
 * pointType.java This file was generated by XMLSpy 2006sp2 Enterprise Edition.
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE OVERWRITTEN WHEN YOU
 * RE-RUN CODE GENERATION. Refer to the XMLSpy Documentation for further
 * details. http://www.altova.com/xmlspy
 */

package com.jmex.model.collada.schema;

public class pointType extends com.jmex.model.collada.xml.Node {

    private static final long serialVersionUID = 1L;

    public pointType(pointType node) {
        super(node);
    }

    public pointType(org.w3c.dom.Node node) {
        super(node);
    }

    public pointType(org.w3c.dom.Document doc) {
        super(doc);
    }

    public pointType(com.jmex.model.collada.xml.Document doc,
            String namespaceURI, String prefix, String name) {
        super(doc, namespaceURI, prefix, name);
    }

    public void adjustPrefix() {
        for (org.w3c.dom.Node tmpNode = getDomFirstChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema", "color"); tmpNode != null; tmpNode = getDomNextChild(
                Element, "http://www.collada.org/2005/11/COLLADASchema",
                "color", tmpNode)) {
            internalAdjustPrefix(tmpNode, true);
            new TargetableFloat3(tmpNode).adjustPrefix();
        }
        for (org.w3c.dom.Node tmpNode = getDomFirstChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "constant_attenuation"); tmpNode != null; tmpNode = getDomNextChild(
                Element, "http://www.collada.org/2005/11/COLLADASchema",
                "constant_attenuation", tmpNode)) {
            internalAdjustPrefix(tmpNode, true);
            new TargetableFloat(tmpNode).adjustPrefix();
        }
        for (org.w3c.dom.Node tmpNode = getDomFirstChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "linear_attenuation"); tmpNode != null; tmpNode = getDomNextChild(
                Element, "http://www.collada.org/2005/11/COLLADASchema",
                "linear_attenuation", tmpNode)) {
            internalAdjustPrefix(tmpNode, true);
            new TargetableFloat(tmpNode).adjustPrefix();
        }
        for (org.w3c.dom.Node tmpNode = getDomFirstChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "quadratic_attenuation"); tmpNode != null; tmpNode = getDomNextChild(
                Element, "http://www.collada.org/2005/11/COLLADASchema",
                "quadratic_attenuation", tmpNode)) {
            internalAdjustPrefix(tmpNode, true);
            new TargetableFloat(tmpNode).adjustPrefix();
        }
    }

    public static int getcolorMinCount() {
        return 1;
    }

    public static int getcolorMaxCount() {
        return 1;
    }

    public int getcolorCount() {
        return getDomChildCount(Element,
                "http://www.collada.org/2005/11/COLLADASchema", "color");
    }

    public boolean hascolor() {
        return hasDomChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema", "color");
    }

    public TargetableFloat3 newcolor() {
        return new TargetableFloat3(domNode.getOwnerDocument().createElementNS(
                "http://www.collada.org/2005/11/COLLADASchema", "color"));
    }

    public TargetableFloat3 getcolorAt(int index) throws Exception {
        return new TargetableFloat3(
                dereference(getDomChildAt(Element,
                        "http://www.collada.org/2005/11/COLLADASchema",
                        "color", index)));
    }

    public org.w3c.dom.Node getStartingcolorCursor() throws Exception {
        return getDomFirstChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema", "color");
    }

    public org.w3c.dom.Node getAdvancedcolorCursor(org.w3c.dom.Node curNode)
            throws Exception {
        return getDomNextChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema", "color",
                curNode);
    }

    public TargetableFloat3 getcolorValueAtCursor(org.w3c.dom.Node curNode)
            throws Exception {
        if (curNode == null)
            throw new com.jmex.model.collada.xml.XmlException("Out of range");
        else
            return new TargetableFloat3(dereference(curNode));
    }

    public TargetableFloat3 getcolor() throws Exception {
        return getcolorAt(0);
    }

    public void removecolorAt(int index) {
        removeDomChildAt(Element,
                "http://www.collada.org/2005/11/COLLADASchema", "color", index);
    }

    public void removecolor() {
        while (hascolor())
            removecolorAt(0);
    }

    public void addcolor(TargetableFloat3 value) {
        appendDomElement("http://www.collada.org/2005/11/COLLADASchema",
                "color", value);
    }

    public void insertcolorAt(TargetableFloat3 value, int index) {
        insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema",
                "color", index, value);
    }

    public void replacecolorAt(TargetableFloat3 value, int index) {
        replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema",
                "color", index, value);
    }

    public static int getconstant_attenuationMinCount() {
        return 0;
    }

    public static int getconstant_attenuationMaxCount() {
        return 1;
    }

    public int getconstant_attenuationCount() {
        return getDomChildCount(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "constant_attenuation");
    }

    public boolean hasconstant_attenuation() {
        return hasDomChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "constant_attenuation");
    }

    public TargetableFloat newconstant_attenuation() {
        return new TargetableFloat(domNode.getOwnerDocument().createElementNS(
                "http://www.collada.org/2005/11/COLLADASchema",
                "constant_attenuation"));
    }

    public TargetableFloat getconstant_attenuationAt(int index)
            throws Exception {
        return new TargetableFloat(dereference(getDomChildAt(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "constant_attenuation", index)));
    }

    public org.w3c.dom.Node getStartingconstant_attenuationCursor()
            throws Exception {
        return getDomFirstChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "constant_attenuation");
    }

    public org.w3c.dom.Node getAdvancedconstant_attenuationCursor(
            org.w3c.dom.Node curNode) throws Exception {
        return getDomNextChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "constant_attenuation", curNode);
    }

    public TargetableFloat getconstant_attenuationValueAtCursor(
            org.w3c.dom.Node curNode) throws Exception {
        if (curNode == null)
            throw new com.jmex.model.collada.xml.XmlException("Out of range");
        else
            return new TargetableFloat(dereference(curNode));
    }

    public TargetableFloat getconstant_attenuation() throws Exception {
        return getconstant_attenuationAt(0);
    }

    public void removeconstant_attenuationAt(int index) {
        removeDomChildAt(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "constant_attenuation", index);
    }

    public void removeconstant_attenuation() {
        while (hasconstant_attenuation())
            removeconstant_attenuationAt(0);
    }

    public void addconstant_attenuation(TargetableFloat value) {
        appendDomElement("http://www.collada.org/2005/11/COLLADASchema",
                "constant_attenuation", value);
    }

    public void insertconstant_attenuationAt(TargetableFloat value, int index) {
        insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema",
                "constant_attenuation", index, value);
    }

    public void replaceconstant_attenuationAt(TargetableFloat value, int index) {
        replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema",
                "constant_attenuation", index, value);
    }

    public static int getlinear_attenuationMinCount() {
        return 0;
    }

    public static int getlinear_attenuationMaxCount() {
        return 1;
    }

    public int getlinear_attenuationCount() {
        return getDomChildCount(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "linear_attenuation");
    }

    public boolean haslinear_attenuation() {
        return hasDomChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "linear_attenuation");
    }

    public TargetableFloat newlinear_attenuation() {
        return new TargetableFloat(domNode.getOwnerDocument().createElementNS(
                "http://www.collada.org/2005/11/COLLADASchema",
                "linear_attenuation"));
    }

    public TargetableFloat getlinear_attenuationAt(int index) throws Exception {
        return new TargetableFloat(dereference(getDomChildAt(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "linear_attenuation", index)));
    }

    public org.w3c.dom.Node getStartinglinear_attenuationCursor()
            throws Exception {
        return getDomFirstChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "linear_attenuation");
    }

    public org.w3c.dom.Node getAdvancedlinear_attenuationCursor(
            org.w3c.dom.Node curNode) throws Exception {
        return getDomNextChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "linear_attenuation", curNode);
    }

    public TargetableFloat getlinear_attenuationValueAtCursor(
            org.w3c.dom.Node curNode) throws Exception {
        if (curNode == null)
            throw new com.jmex.model.collada.xml.XmlException("Out of range");
        else
            return new TargetableFloat(dereference(curNode));
    }

    public TargetableFloat getlinear_attenuation() throws Exception {
        return getlinear_attenuationAt(0);
    }

    public void removelinear_attenuationAt(int index) {
        removeDomChildAt(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "linear_attenuation", index);
    }

    public void removelinear_attenuation() {
        while (haslinear_attenuation())
            removelinear_attenuationAt(0);
    }

    public void addlinear_attenuation(TargetableFloat value) {
        appendDomElement("http://www.collada.org/2005/11/COLLADASchema",
                "linear_attenuation", value);
    }

    public void insertlinear_attenuationAt(TargetableFloat value, int index) {
        insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema",
                "linear_attenuation", index, value);
    }

    public void replacelinear_attenuationAt(TargetableFloat value, int index) {
        replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema",
                "linear_attenuation", index, value);
    }

    public static int getquadratic_attenuationMinCount() {
        return 0;
    }

    public static int getquadratic_attenuationMaxCount() {
        return 1;
    }

    public int getquadratic_attenuationCount() {
        return getDomChildCount(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "quadratic_attenuation");
    }

    public boolean hasquadratic_attenuation() {
        return hasDomChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "quadratic_attenuation");
    }

    public TargetableFloat newquadratic_attenuation() {
        return new TargetableFloat(domNode.getOwnerDocument().createElementNS(
                "http://www.collada.org/2005/11/COLLADASchema",
                "quadratic_attenuation"));
    }

    public TargetableFloat getquadratic_attenuationAt(int index)
            throws Exception {
        return new TargetableFloat(dereference(getDomChildAt(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "quadratic_attenuation", index)));
    }

    public org.w3c.dom.Node getStartingquadratic_attenuationCursor()
            throws Exception {
        return getDomFirstChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "quadratic_attenuation");
    }

    public org.w3c.dom.Node getAdvancedquadratic_attenuationCursor(
            org.w3c.dom.Node curNode) throws Exception {
        return getDomNextChild(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "quadratic_attenuation", curNode);
    }

    public TargetableFloat getquadratic_attenuationValueAtCursor(
            org.w3c.dom.Node curNode) throws Exception {
        if (curNode == null)
            throw new com.jmex.model.collada.xml.XmlException("Out of range");
        else
            return new TargetableFloat(dereference(curNode));
    }

    public TargetableFloat getquadratic_attenuation() throws Exception {
        return getquadratic_attenuationAt(0);
    }

    public void removequadratic_attenuationAt(int index) {
        removeDomChildAt(Element,
                "http://www.collada.org/2005/11/COLLADASchema",
                "quadratic_attenuation", index);
    }

    public void removequadratic_attenuation() {
        while (hasquadratic_attenuation())
            removequadratic_attenuationAt(0);
    }

    public void addquadratic_attenuation(TargetableFloat value) {
        appendDomElement("http://www.collada.org/2005/11/COLLADASchema",
                "quadratic_attenuation", value);
    }

    public void insertquadratic_attenuationAt(TargetableFloat value, int index) {
        insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema",
                "quadratic_attenuation", index, value);
    }

    public void replacequadratic_attenuationAt(TargetableFloat value, int index) {
        replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema",
                "quadratic_attenuation", index, value);
    }

    private org.w3c.dom.Node dereference(org.w3c.dom.Node node) {
        return node;
    }
}
