/**
 * SpringType.java This file was generated by XMLSpy 2006sp2 Enterprise Edition.
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE OVERWRITTEN WHEN YOU
 * RE-RUN CODE GENERATION. Refer to the XMLSpy Documentation for further
 * details. http://www.altova.com/xmlspy
 */

package com.jmex.model.collada.schema;

import com.jmex.model.collada.types.SchemaNMToken;

public class SpringType extends SchemaNMToken {

    private static final long serialVersionUID = 1L;
    public static final int ELINEAR = 0; /* LINEAR */
    public static final int EANGULAR = 1; /* ANGULAR */

    public static String[] sEnumValues = { "LINEAR", "ANGULAR", };

    public SpringType() {
        super();
    }

    public SpringType(String newValue) {
        super(newValue);
        validate();
    }

    public SpringType(SchemaNMToken newValue) {
        super(newValue);
        validate();
    }

    public static int getEnumerationCount() {
        return sEnumValues.length;
    }

    public static String getEnumerationValue(int index) {
        return sEnumValues[index];
    }

    public static boolean isValidEnumerationValue(String val) {
        for (int i = 0; i < sEnumValues.length; i++) {
            if (val.equals(sEnumValues[i]))
                return true;
        }
        return false;
    }

    public void validate() {

        if (!isValidEnumerationValue(toString()))
            throw new com.jmex.model.collada.xml.XmlException(
                    "Value of SpringType is invalid.");
    }
}
