/**
 * technique_commonType8.java
 *
 * This file was generated by XMLSpy 2007sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.jmex.model.collada.schema;


public class technique_commonType8 extends com.jmex.xml.xml.Node {

	public technique_commonType8(technique_commonType8 node) {
		super(node);
	}

	public technique_commonType8(org.w3c.dom.Node node) {
		super(node);
	}

	public technique_commonType8(org.w3c.dom.Document doc) {
		super(doc);
	}

	public technique_commonType8(com.jmex.xml.xml.Document doc, String namespaceURI, String prefix, String name) {
		super(doc, namespaceURI, prefix, name);
	}
	
	public void adjustPrefix() {
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "enabled" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "enabled", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
			new enabledType(tmpNode).adjustPrefix();
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "interpenetrate" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "interpenetrate", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
			new interpenetrateType(tmpNode).adjustPrefix();
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "limits" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "limits", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
			new limitsType(tmpNode).adjustPrefix();
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "spring" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "spring", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
			new springType2(tmpNode).adjustPrefix();
		}
	}
	public void setXsiType() {
 		org.w3c.dom.Element el = (org.w3c.dom.Element) domNode;
		el.setAttributeNS("http://www.w3.org/2001/XMLSchema-instance", "xsi:type", "technique_common");
	}

	public static int getenabledMinCount() {
		return 0;
	}

	public static int getenabledMaxCount() {
		return 1;
	}

	public int getenabledCount() {
		return getDomChildCount(Element, "http://www.collada.org/2005/11/COLLADASchema", "enabled");
	}

	public boolean hasenabled() {
		return hasDomChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "enabled");
	}

	public enabledType newenabled() {
		return new enabledType(domNode.getOwnerDocument().createElementNS("http://www.collada.org/2005/11/COLLADASchema", "enabled"));
	}

	public enabledType getenabledAt(int index) throws Exception {
		return new enabledType(getDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "enabled", index));
	}

	public org.w3c.dom.Node getStartingenabledCursor() throws Exception {
		return getDomFirstChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "enabled" );
	}

	public org.w3c.dom.Node getAdvancedenabledCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "enabled", curNode );
	}

	public enabledType getenabledValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new enabledType(curNode);
	}

	public enabledType getenabled() throws Exception 
 {
		return getenabledAt(0);
	}

	public void removeenabledAt(int index) {
		removeDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "enabled", index);
	}

	public void removeenabled() {
		removeenabledAt(0);
	}

	public org.w3c.dom.Node addenabled(enabledType value) {
		return appendDomElement("http://www.collada.org/2005/11/COLLADASchema", "enabled", value);
	}

	public void insertenabledAt(enabledType value, int index) {
		insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "enabled", index, value);
	}

	public void replaceenabledAt(enabledType value, int index) {
		replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "enabled", index, value);
	}

	public static int getinterpenetrateMinCount() {
		return 0;
	}

	public static int getinterpenetrateMaxCount() {
		return 1;
	}

	public int getinterpenetrateCount() {
		return getDomChildCount(Element, "http://www.collada.org/2005/11/COLLADASchema", "interpenetrate");
	}

	public boolean hasinterpenetrate() {
		return hasDomChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "interpenetrate");
	}

	public interpenetrateType newinterpenetrate() {
		return new interpenetrateType(domNode.getOwnerDocument().createElementNS("http://www.collada.org/2005/11/COLLADASchema", "interpenetrate"));
	}

	public interpenetrateType getinterpenetrateAt(int index) throws Exception {
		return new interpenetrateType(getDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "interpenetrate", index));
	}

	public org.w3c.dom.Node getStartinginterpenetrateCursor() throws Exception {
		return getDomFirstChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "interpenetrate" );
	}

	public org.w3c.dom.Node getAdvancedinterpenetrateCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "interpenetrate", curNode );
	}

	public interpenetrateType getinterpenetrateValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new interpenetrateType(curNode);
	}

	public interpenetrateType getinterpenetrate() throws Exception 
 {
		return getinterpenetrateAt(0);
	}

	public void removeinterpenetrateAt(int index) {
		removeDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "interpenetrate", index);
	}

	public void removeinterpenetrate() {
		removeinterpenetrateAt(0);
	}

	public org.w3c.dom.Node addinterpenetrate(interpenetrateType value) {
		return appendDomElement("http://www.collada.org/2005/11/COLLADASchema", "interpenetrate", value);
	}

	public void insertinterpenetrateAt(interpenetrateType value, int index) {
		insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "interpenetrate", index, value);
	}

	public void replaceinterpenetrateAt(interpenetrateType value, int index) {
		replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "interpenetrate", index, value);
	}

	public static int getlimitsMinCount() {
		return 0;
	}

	public static int getlimitsMaxCount() {
		return 1;
	}

	public int getlimitsCount() {
		return getDomChildCount(Element, "http://www.collada.org/2005/11/COLLADASchema", "limits");
	}

	public boolean haslimits() {
		return hasDomChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "limits");
	}

	public limitsType newlimits() {
		return new limitsType(domNode.getOwnerDocument().createElementNS("http://www.collada.org/2005/11/COLLADASchema", "limits"));
	}

	public limitsType getlimitsAt(int index) throws Exception {
		return new limitsType(getDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "limits", index));
	}

	public org.w3c.dom.Node getStartinglimitsCursor() throws Exception {
		return getDomFirstChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "limits" );
	}

	public org.w3c.dom.Node getAdvancedlimitsCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "limits", curNode );
	}

	public limitsType getlimitsValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new limitsType(curNode);
	}

	public limitsType getlimits() throws Exception 
 {
		return getlimitsAt(0);
	}

	public void removelimitsAt(int index) {
		removeDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "limits", index);
	}

	public void removelimits() {
		removelimitsAt(0);
	}

	public org.w3c.dom.Node addlimits(limitsType value) {
		return appendDomElement("http://www.collada.org/2005/11/COLLADASchema", "limits", value);
	}

	public void insertlimitsAt(limitsType value, int index) {
		insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "limits", index, value);
	}

	public void replacelimitsAt(limitsType value, int index) {
		replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "limits", index, value);
	}

	public static int getspringMinCount() {
		return 0;
	}

	public static int getspringMaxCount() {
		return 1;
	}

	public int getspringCount() {
		return getDomChildCount(Element, "http://www.collada.org/2005/11/COLLADASchema", "spring");
	}

	public boolean hasspring() {
		return hasDomChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "spring");
	}

	public springType2 newspring() {
		return new springType2(domNode.getOwnerDocument().createElementNS("http://www.collada.org/2005/11/COLLADASchema", "spring"));
	}

	public springType2 getspringAt(int index) throws Exception {
		return new springType2(getDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "spring", index));
	}

	public org.w3c.dom.Node getStartingspringCursor() throws Exception {
		return getDomFirstChild(Element, "http://www.collada.org/2005/11/COLLADASchema", "spring" );
	}

	public org.w3c.dom.Node getAdvancedspringCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, "http://www.collada.org/2005/11/COLLADASchema", "spring", curNode );
	}

	public springType2 getspringValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.jmex.xml.xml.XmlException("Out of range");
		else
			return new springType2(curNode);
	}

	public springType2 getspring() throws Exception 
 {
		return getspringAt(0);
	}

	public void removespringAt(int index) {
		removeDomChildAt(Element, "http://www.collada.org/2005/11/COLLADASchema", "spring", index);
	}

	public void removespring() {
		removespringAt(0);
	}

	public org.w3c.dom.Node addspring(springType2 value) {
		return appendDomElement("http://www.collada.org/2005/11/COLLADASchema", "spring", value);
	}

	public void insertspringAt(springType2 value, int index) {
		insertDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "spring", index, value);
	}

	public void replacespringAt(springType2 value, int index) {
		replaceDomElementAt("http://www.collada.org/2005/11/COLLADASchema", "spring", index, value);
	}

}
