/**
 * SchemaLanguage.java
 *
 * This file was generated by XMLSpy 2007sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package com.jmex.xml.types;

public class SchemaLanguage extends SchemaToken {
	public SchemaLanguage() {
		super();
	}

	public SchemaLanguage(String newvalue) {
		super(newvalue);
	}

	public SchemaLanguage(SchemaLanguage newvalue) {
		super((SchemaToken)newvalue);
	}
}
